//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yasemin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITY_RESTAURANT
    {
        public int CityRestaurantId { get; set; }
        public int CityId { get; set; }
        public int RestaurantId { get; set; }
    
        public virtual CITY CITY { get; set; }
        public virtual RESTAURANT RESTAURANT { get; set; }
    }
}
