//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yasemin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOOD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FOOD()
        {
            this.ORDER_FOOD = new HashSet<ORDER_FOOD>();
        }
    
        public int FoodId { get; set; }
        public string FoodName { get; set; }
        public int FoodPrice { get; set; }
        public int CategoryId { get; set; }
        public int RestaurantId { get; set; }
        public string FoodLogo { get; set; }
        public string FoodDescription { get; set; }
        public Nullable<int> FoodAmount { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_FOOD> ORDER_FOOD { get; set; }
        public virtual RESTAURANT RESTAURANT { get; set; }

        public int TotalPrice { get; set; }
    }
}
