//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yasemin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbFoodOrderingSystemEntities : DbContext
    {
        public DbFoodOrderingSystemEntities()
            : base("name=DbFoodOrderingSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN_FOOD> ADMIN_FOOD { get; set; }
        public virtual DbSet<CATEGORY> CATEGORY { get; set; }
        public virtual DbSet<CITY> CITY { get; set; }
        public virtual DbSet<CITY_RESTAURANT> CITY_RESTAURANT { get; set; }
        public virtual DbSet<CONCEPT> CONCEPT { get; set; }
        public virtual DbSet<CONCEPT_RESTAURANT> CONCEPT_RESTAURANT { get; set; }
        public virtual DbSet<FOOD> FOOD { get; set; }
        public virtual DbSet<MEMBER> MEMBER { get; set; }
        public virtual DbSet<ORDER_FOOD> ORDER_FOOD { get; set; }
        public virtual DbSet<ORDER_USER> ORDER_USER { get; set; }
        public virtual DbSet<ORDERS> ORDERS { get; set; }
        public virtual DbSet<RESTAURANT> RESTAURANT { get; set; }
        public virtual DbSet<SCORE> SCORE { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<USER_ADDRESS> USER_ADDRESS { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
    }
}
