//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yasemin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MEMBER
    {   
        public int MemberId { get; set; }
        
        public string MemberMail { get; set; }
        public int MemberPassword { get; set; }
        public string MemberRole { get; set; }
    
        public virtual ADMIN_FOOD ADMIN_FOOD { get; set; }
        public virtual RESTAURANT RESTAURANT { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
