//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yasemin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_USER
    {
        public int OrderUser { get; set; }
        public int OrderId { get; set; }
        public int UserId { get; set; }
    
        public virtual ORDERS ORDERS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
